// Generated from the certified temporary PostgreSQL database. Do not edit manually.
export interface CtDatabaseRowMap {
  "client_account_notifications": {
    "id": string;
    "client_id": string;
    "account_id": string;
    "category": string;
    "status": string;
    "notification_key": string;
    "source_action_id": string | null;
    "metadata_safe": unknown;
    "created_at": string;
    "resolved_at": string | null;
    "read_at": string | null;
    "action_required": boolean;
    "action_completed_at": string | null;
    "action_outcome": string | null;
    "action_ref_type": string | null;
    "action_ref_id": string | null;
  };
  "ct_email_contract_references": {
    "contract_key": string;
    "audience_plan": string;
    "action_ref_type": string;
    "payload_schema_version": string;
    "enabled": boolean;
    "created_at": string;
  };
  "ct_proposal_batches": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "snapshot_id": string;
    "status": string;
    "trigger_reason": string;
    "idempotency_key": string;
    "ready_at": string | null;
    "review_expires_at": string | null;
    "claimed_at": string | null;
    "claim_token": string | null;
    "completed_at": string | null;
    "frozen_reason": string | null;
    "version": number;
    "created_at": string;
    "updated_at": string;
  };
  "ct_proposal_events": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "batch_id": string;
    "proposal_id": string | null;
    "event_type": string;
    "actor_type": string;
    "actor_id": string | null;
    "idempotency_key": string;
    "payload_safe": unknown;
    "occurred_at": string;
    "created_at": string;
  };
  "ct_proposals": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "batch_id": string;
    "snapshot_id": string;
    "replacement_of_target_id": string | null;
    "normalized_username": string;
    "display_username": string;
    "candidate_data": unknown;
    "score": number;
    "score_breakdown": unknown;
    "scoring_version": string;
    "eligibility_status": string;
    "exclusion_reasons": string[];
    "status": string;
    "decision_actor_type": string | null;
    "decision_actor_id": string | null;
    "decided_at": string | null;
    "activated_target_id": string | null;
    "activation_idempotency_key": string | null;
    "activation_error_code": string | null;
    "version": number;
    "created_at": string;
    "updated_at": string;
  };
  "ct_target_audit_events": {
    "id": string;
    "created_at": string;
    "account_id": string;
    "target_id": string | null;
    "operation": string;
    "result": string;
    "reason": string | null;
    "actor_type": string;
    "actor_id": string | null;
    "batch_id": string | null;
    "counts": unknown | null;
    "metadata_safe": unknown;
  };
  "ct_target_availability_assessments": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "assessment_key": string;
    "normalized_username": string;
    "stable_platform_user_id": string | null;
    "status": string;
    "confidence": string;
    "identity_resolution": string;
    "reason_codes": string[];
    "evidence_count": number;
    "distinct_run_count": number;
    "distinct_device_count": number;
    "latest_observed_at": string | null;
    "recheck_required": boolean;
    "next_recheck_at": string | null;
    "quarantine_recommended": boolean;
    "quarantine_until": string | null;
    "terminal_proof": boolean;
    "assessed_at": string;
    "model_version": string;
    "created_at": string;
  };
  "ct_target_availability_current": {
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "assessment_id": string;
    "updated_at": string;
  };
  "ct_target_availability_observations": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "observed_at": string;
    "source": string;
    "source_run_id": string | null;
    "source_worker": string | null;
    "worker_version": string | null;
    "source_device_key": string | null;
    "instagram_version": string | null;
    "searched_username": string;
    "observed_username": string | null;
    "observed_stable_platform_user_id": string | null;
    "lookup_result": string;
    "profile_found": boolean | null;
    "verified_badge": boolean | null;
    "followers_surface": string;
    "accessible_profiles_count": number | null;
    "terminal_end_detected": boolean;
    "repeated_first_profiles_detected": boolean;
    "retry_count": number;
    "retry_budget_exhausted": boolean;
    "navigation_timeout": boolean;
    "recovery_outcome": string;
    "ui_evidence_quality": string;
    "network_state": string;
    "session_state": string;
    "reason_codes": string[];
    "idempotency_key": string;
    "evidence_safe": unknown;
    "created_at": string;
  };
  "ct_target_evaluated_profiles": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "normalized_username": string;
    "first_event_id": string;
    "first_evaluated_at": string;
    "first_business_date": string;
    "created_at": string;
  };
  "ct_target_evaluation_events": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "normalized_username": string;
    "evaluated_at": string;
    "business_date": string;
    "outcome": string;
    "source_run_id": string | null;
    "source_worker": string | null;
    "attribution_reliability": string;
    "worker_version": string | null;
    "idempotency_key": string;
    "metadata_safe": unknown;
    "created_at": string;
  };
  "ct_target_identity_current": {
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "current_username": string;
    "stable_platform_user_id": string | null;
    "identity_status": string;
    "confidence": string;
    "last_history_id": string | null;
    "last_observed_at": string;
    "updated_at": string;
  };
  "ct_target_identity_history": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "observation_id": string | null;
    "previous_username": string;
    "observed_username": string | null;
    "stable_platform_user_id": string | null;
    "resolution": string;
    "confidence": string;
    "reason_codes": string[];
    "idempotency_key": string;
    "observed_at": string;
    "created_at": string;
  };
  "ct_target_lifecycle_assessments": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "assessment_key": string;
    "status": string;
    "utilization_ratio": number | null;
    "unique_profiles_evaluated": number;
    "estimated_exploitable_audience": number | null;
    "denominator_source": string;
    "denominator_version": string;
    "confidence": string;
    "reason_codes": string[];
    "replacement_state": string;
    "assessed_at": string;
    "archived_at": string | null;
    "archive_reason": string | null;
    "created_at": string;
  };
  "ct_target_lifecycle_current": {
    "tenant_id": string;
    "account_id": string;
    "target_id": string;
    "assessment_id": string;
    "updated_at": string;
  };
  "ct_target_lifecycle_stock_v1": {
    "account_id": string | null;
    "stock_count": number | null;
    "replacement_pending_in_stock": number | null;
    "exhausted_in_stock": number | null;
  };
  "ct_target_performance_aggregates": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "source_target_id": string;
    "window_kind": string;
    "window_start_business_date": string;
    "window_end_business_date": string;
    "follows": number;
    "followbacks": number;
    "fbr": number | null;
    "reliability": string;
    "reason": string;
    "source_version": string;
    "computed_at": string;
    "created_at": string;
    "updated_at": string;
  };
  "ct_target_performance_observations": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "source_target_id": string;
    "business_date": string;
    "window_kind": string;
    "follows": number;
    "followbacks": number;
    "fbr": number | null;
    "reliability": string;
    "reason": string;
    "observed_at": string;
    "source_event_key": string;
    "metadata_safe": unknown;
    "created_at": string;
  };
  "ct_target_replacement_links": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "proposal_id": string;
    "replaced_target_id": string;
    "replacement_target_id": string | null;
    "state": string;
    "ready_at": string | null;
    "completed_at": string | null;
    "created_at": string;
    "updated_at": string;
  };
  "ct_target_verification_jobs": {
    "id": string;
    "target_id": string;
    "account_id": string;
    "batch_id": string | null;
    "normalized_username": string;
    "status": string;
    "attempt_count": number;
    "max_attempts": number;
    "next_attempt_at": string | null;
    "locked_at": string | null;
    "locked_by": string | null;
    "last_error_code": string | null;
    "last_error_message": string | null;
    "provider_status": string | null;
    "metadata_safe": unknown;
    "created_at": string;
    "updated_at": string;
  };
  "ct_target_verification_scheduler_locks": {
    "lock_key": string;
    "worker_id": string;
    "locked_at": string;
    "expires_at": string;
  };
  "ct_targeting_criteria_snapshots": {
    "id": string;
    "tenant_id": string;
    "account_id": string;
    "plan": string;
    "entitlement_id": string;
    "entitlement_version": string;
    "eligible_target_count": number;
    "active_targets": unknown;
    "blacklist_fingerprint": string;
    "languages": unknown;
    "geographies": unknown;
    "niches": unknown;
    "follower_range": unknown;
    "engagement_expectations": unknown;
    "account_analysis_data": unknown;
    "target_performance_summary": unknown;
    "lifecycle_summary": unknown;
    "scoring_config_version": string;
    "search_strategy_version": string;
    "review_duration": string;
    "batch_size": number;
    "rejection_cooldown": string;
    "trigger_reason": string;
    "canonical_payload": unknown;
    "fingerprint": string;
    "created_at": string;
  };
}

export interface CtDatabaseRpcMap {
  "ct_activate_premium_proposal_v1(uuid,uuid,uuid,text,timestamp with time zone)": { readonly name: "ct_activate_premium_proposal_v1"; readonly result: "jsonb" };
  "ct_archive_target_v1_disabled(uuid)": { readonly name: "ct_archive_target_v1_disabled"; readonly result: "void" };
  "ct_assert_service_role_v1()": { readonly name: "ct_assert_service_role_v1"; readonly result: "void" };
  "ct_claim_expired_premium_batch_v1(text,timestamp with time zone)": { readonly name: "ct_claim_expired_premium_batch_v1"; readonly result: "jsonb" };
  "ct_create_premium_proposal_batch_v1(uuid,uuid,text,text,jsonb,jsonb,timestamp with time zone)": { readonly name: "ct_create_premium_proposal_batch_v1"; readonly result: "jsonb" };
  "ct_decide_premium_proposal_v1(uuid,uuid,uuid,text,text,timestamp with time zone)": { readonly name: "ct_decide_premium_proposal_v1"; readonly result: "jsonb" };
  "ct_decide_premium_proposals_bulk_v1(uuid,uuid[],uuid,text,text,timestamp with time zone)": { readonly name: "ct_decide_premium_proposals_bulk_v1"; readonly result: "jsonb" };
  "ct_finalize_premium_batch_v1(uuid,timestamp with time zone)": { readonly name: "ct_finalize_premium_batch_v1"; readonly result: "jsonb" };
  "ct_freeze_or_cancel_premium_batch_v1(uuid,text,boolean,timestamp with time zone)": { readonly name: "ct_freeze_or_cancel_premium_batch_v1"; readonly result: "jsonb" };
  "ct_recompute_target_lifecycle_v1(uuid,uuid,integer,text,text,text,text,timestamp with time zone)": { readonly name: "ct_recompute_target_lifecycle_v1"; readonly result: "jsonb" };
  "ct_record_target_evaluation_event_v1(uuid,uuid,text,timestamp with time zone,text,uuid,text,text,text,text,jsonb)": { readonly name: "ct_record_target_evaluation_event_v1"; readonly result: "jsonb" };
  "ct_reject_append_only_mutation_v1()": { readonly name: "ct_reject_append_only_mutation_v1"; readonly result: "trigger" };
  "ct_resolve_owned_premium_account_v1(uuid,uuid)": { readonly name: "ct_resolve_owned_premium_account_v1"; readonly result: "TABLE(tenant_id uuid, entitlement_id uuid, entitlement_version text)" };
}
