export type RestaurantLang = "fr" | "en";

export const RESTAURANT_LANG_KEY = "restaurant_call_assistant_lang_v1";
export const RESTAURANT_LANG_COOKIE = "restaurant_lang";

export function isRestaurantLang(value: unknown): value is RestaurantLang {
  return value === "fr" || value === "en";
}

export const restaurantCommonCopy = {
  fr: {
    langFr: "FR",
    langEn: "EN",
    backToService: "Retour à la page service",
    backToLogin: "Retour à la connexion",
    email: "Email",
    password: "Mot de passe",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    login: {
      brandSub: "Accès client restaurant",
      eyebrow: "Espace client",
      title: "Connexion à l'espace restaurant",
      text: "Connecte-toi pour accéder à ton espace AI Restaurant Call Assistant : appels, réservations, escalades, qualité et performance par site.",
      badges: ["Accès sécurisé", "Espace restaurant", "Données protégées"],
      passwordPlaceholder: "Entre ton mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      emptyError: "Entre un email et un mot de passe pour continuer.",
      sessionError: "Impossible d'ouvrir une session sécurisée.",
      accessError: "Impossible de charger ton accès restaurant.",
      failed: "Échec de connexion.",
      loading: "Ouverture de l'espace...",
      submit: "Connexion",
      helper: "Ton accès est protégé et sécurisé.",
    },
    forgot: {
      brandSub: "Récupération du mot de passe",
      eyebrow: "Réinitialiser l'accès",
      title: "Réinitialise ton mot de passe restaurant",
      text: "Entre l'email lié à ton compte AI Restaurant Call Assistant. Nous enverrons un lien sécurisé pour continuer.",
      emptyError: "Entre ton email client restaurant pour recevoir un lien de réinitialisation.",
      success: "Email de réinitialisation envoyé. Vérifie ta boîte mail et ouvre le lien sécurisé.",
      failed: "Impossible d'envoyer l'email de réinitialisation.",
      loading: "Envoi de l'email...",
      submit: "Envoyer l'email",
      helper: "Le lien de réinitialisation ouvrira la page sécurisée.",
    },
    reset: {
      brandSub: "Réinitialisation du mot de passe",
      eyebrow: "Récupération sécurisée",
      title: "Crée un nouveau mot de passe restaurant",
      text: "Utilise le lien sécurisé reçu par email pour créer un nouveau mot de passe pour ton espace AI Restaurant Call Assistant.",
      checking: "Validation du lien de réinitialisation...",
      invalid: "Ce lien de réinitialisation est invalide ou expiré.",
      success: "Ton mot de passe a été mis à jour. Tu peux maintenant te connecter avec ton nouveau mot de passe.",
      passwordPlaceholder: "Entre un nouveau mot de passe",
      confirmPlaceholder: "Confirme ton nouveau mot de passe",
      shortPassword: "Le mot de passe doit contenir au moins 8 caractères.",
      mismatch: "Les mots de passe ne correspondent pas.",
      failed: "Impossible de mettre à jour ton mot de passe.",
      loading: "Mise à jour...",
      submit: "Mettre à jour le mot de passe",
    },
    dashboard: {
      nav: {
        overview: "Vue globale",
        locations: "Sites",
        handoffs: "Escalades",
        quality: "Qualité",
      },
      activeProduct: "Produit actif",
      mode: "Mode restaurant",
      servicePage: "Page service",
      clientLogin: "Connexion client",
      logout: "Déconnexion",
      signingOut: "Déconnexion...",
      home: "Accueil",
      restaurantAnalytics: "Analytics restaurant",
      last30Days: "30 derniers jours",
      liveData: "Données live",
      error: "Erreur",
      supabaseError: "Données indisponibles",
      overview: {
        eyebrow: "Analytics restaurant",
        title: "Performance de ton restaurant",
        text: "Tes données filtrées sur ton restaurant : volume d'appels, appels complétés, escalades, demandes non résolues et performance par site.",
        totalCalls: "Total appels",
        totalCallsDetail: "Appels entrants reçus sur tes sites.",
        completedCalls: "Appels complétés",
        completedCallsDetail: "Appels résolus sans intervention manuelle.",
        escalations: "Escalades",
        escalationsDetail: "Escalades humaines créées avec contexte et priorité.",
        fallbacks: "À revoir",
        fallbacksDetail: "Appels qui ont nécessité une réponse de secours ou un traitement manuel.",
        businessInsights: "Insights business",
        revenueProtection: "Protection du revenu",
        businessDescription: "Signaux pour comprendre les risques, réservations manquées, frustration ou suivis équipe.",
        topEscalationReasons: "Principales raisons d'escalade",
        fallbackMissed: "Opportunités manquées",
        frustrated: "Clients frustrés détectés",
        followUp: "Appels à suivre",
        noEscalations: "Aucune escalade",
        needsReview: "À revoir",
        locationsTitle: "Tes sites",
        bookingsHeader: "Réservations",
        reviewHeader: "À revoir",
        locationEyebrow: "Performance par site",
        locationDescription: "Performance par site filtrée sur ton restaurant.",
        unavailable: "Données indisponibles",
        loadErrorTitle: "Impossible de charger la vue globale.",
      },
      locations: {
        eyebrow: "Performance par site",
        title: "Sites",
        description: "Ouvre un site restaurant pour consulter ses appels, réservations, escalades et indicateurs qualité.",
        listTitle: "Liste des sites",
        listEyebrow: "Sites restaurant",
        listDescription: "Choisis un site pour afficher ses appels, réservations et escalades.",
        noLocationsTitle: "Aucun site trouvé",
        noLocationsText: "Aucun site n'est disponible pour ton périmètre.",
        loadErrorTitle: "Impossible de charger les sites.",
      },
      locationDetail: {
        eyebrow: "Détail du site",
        description: "Vue opérationnelle du site : appels, réservations, escalades, demandes non résolues et qualité locale.",
        locationScope: "Vue site",
        calls: "Appels du site",
        callsDetail: "Appels entrants pour ce site restaurant.",
        bookings: "Réservations",
        bookingsDetail: "Réservations capturées ou qualifiées par l'IA.",
        handoffs: "Escalades",
        handoffsDetail: "Appels transmis à l'équipe avec contexte.",
        fallbacks: "À revoir",
        fallbacksDetail: "Appels nécessitant une réponse de secours ou un contrôle humain.",
        recentCalls: "Appels récents",
        callActivity: "Activité appels",
        recentDescription: "Appels ou escalades récents pour ce site.",
        localTuning: "Optimisation locale",
        recommendations: "Recommandations",
        tuningDescription: "Signaux locaux pour améliorer les réponses, la FAQ, l'équipe et le traitement des demandes.",
        recommendationHandoff: "des appels de ce site demandent une escalade. Vérifie les motifs principaux et le contexte transmis avant les périodes de forte activité.",
        recommendationFallback: "des appels de ce site nécessitent une réponse de secours. Vérifie la FAQ, les horaires, le menu et les règles de réservation.",
        recommendationClear: "Aucun signal d'optimisation urgent n'est visible pour ce site actuellement.",
        noAnalyticsTitle: "Aucune donnée site trouvée",
        noAnalyticsText: "Aucun résumé n'est disponible pour ce site dans ton périmètre.",
        noRecentTitle: "Aucun appel récent",
        noRecentText: "Aucun appel ou escalade récent pour ce site.",
        noSignalTitle: "Aucun signal d'optimisation",
        noSignalText: "Aucun signal qualité n'est disponible pour ce site.",
        loadErrorTitle: "Impossible de charger ce site.",
      },
      handoffs: {
        eyebrow: "Escalade humaine",
        title: "Escalades",
        description: "Suis les appels qui ont demandé une intervention humaine : priorité, raison, site, contexte et état de résolution.",
        operationsQueue: "File opérations",
        open: "Escalades ouvertes",
        openDetail: "Escalades en attente d'action équipe.",
        resolvedToday: "Résolus aujourd'hui",
        resolvedDetail: "Escalades clôturées par l'équipe aujourd'hui.",
        avgAssignment: "Assignation moyenne",
        avgDetail: "Temps moyen avant assignation à l'équipe.",
        highPriority: "Haute priorité",
        highDetail: "Demandes sensibles à traiter plus vite.",
        queueTitle: "File des escalades",
        queueEyebrow: "Liste d'escalades",
        queueDescription: "Demandes en cours selon ton périmètre d'exploitation.",
        noHandoffsTitle: "Aucune escalade trouvée",
        noHandoffsText: "Aucune demande d'intervention humaine pour ton périmètre.",
        loadErrorTitle: "Impossible de charger les escalades.",
      },
      quality: {
        eyebrow: "Assurance qualité",
        title: "Qualité",
        description: "Analyse la précision de l'assistant, la mémoire client, la qualité des escalades et la préparation opérationnelle.",
        qaQueue: "File QA",
        noDataTitle: "Aucune donnée qualité trouvée",
        noDataText: "Aucune donnée qualité ou escalade n'est disponible pour ton périmètre.",
        summaryTitle: "Résumé qualité",
        summaryEyebrow: "Revue QA",
        summaryDescription: "Contrôles qualité opérationnels : compréhension des appels, revue des échanges, escalades et mémoire client.",
        metrics: {
          intentAccuracy: "Précision d'intention",
          memoryMatch: "Taux mémoire client",
          handoffCompleteness: "Qualité des escalades",
          reminderCoverage: "Couverture rappels",
        },
        reviewedCalls: "Appels revus",
        reviewedDetail: "Appels échantillonnés pour QA sur la période.",
        passRate: "Taux de réussite",
        passDetail: "Appels respectant les standards qualité.",
        needsTuning: "À optimiser",
        needsTuningDetail: "Appels marqués pour amélioration prompt ou routing.",
        criticalQa: "QA critique",
        criticalDetail: "Problèmes qualité à revoir immédiatement.",
        reviewQueue: "File de revue",
        nextActions: "Prochaines actions",
        reviewDescription: "Notes qualité, revues d'échanges et actions d'amélioration.",
        noReviewTitle: "Aucune action QA",
        noReviewText: "Aucune action qualité disponible pour ton périmètre.",
        topEscalation: "Principales raisons d'escalade",
        handoffDrivers: "Motifs d'escalade",
        escalationDescription: "Raisons pour lesquelles les appels sortent de l'automatisation.",
        noEscalationTitle: "Aucune raison d'escalade",
        noEscalationText: "Aucune raison d'escalade disponible pour ton périmètre.",
        missedTitle: "Opportunités manquées",
        leakage: "Fuite de revenu",
        missedDescription: "Risques de conversion liés à des informations manquantes, réservations incomplètes ou demandes non finalisées.",
        noFallbackTitle: "Aucune opportunité manquée",
        noFallbackText: "Aucun manque à gagner détecté pour ton périmètre.",
        frustratedTitle: "Clients frustrés détectés",
        sentiment: "Monitoring sentiment",
        frustratedDescription: "Signaux à revoir avant avis négatif ou perte de client fidèle.",
        noFrustrationTitle: "Aucun signal de frustration",
        noFrustrationText: "Aucun signal de frustration ou d'urgence pour ton périmètre.",
        followUpTitle: "Appels à suivre",
        openLoop: "Boucle opérationnelle",
        followUpDescription: "Appels à transmettre à l'équipe, au manager ou à un rappel client.",
        noFollowUpTitle: "Aucun appel à suivre",
        noFollowUpText: "Aucune action de suivi attachée aux appels dans ton périmètre.",
        loadErrorTitle: "Impossible de charger les données qualité.",
      },
    },
  },
  en: {
    langFr: "FR",
    langEn: "EN",
    backToService: "Back to service page",
    backToLogin: "Back to login",
    email: "Email",
    password: "Password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    login: {
      brandSub: "Restaurant client access",
      eyebrow: "Client dashboard",
      title: "Restaurant analytics login",
      text: "Sign in to access your AI Restaurant Call Assistant workspace for calls, bookings, escalations, quality, and site-level performance.",
      badges: ["Secure access", "Restaurant workspace", "Protected data"],
      passwordPlaceholder: "Enter your password",
      forgotPassword: "Forgot password?",
      emptyError: "Enter an email and password to continue.",
      sessionError: "Could not open a secure session.",
      accessError: "Could not load restaurant dashboard access.",
      failed: "Login failed.",
      loading: "Opening dashboard...",
      submit: "Login",
      helper: "Your access is protected and secure.",
    },
    forgot: {
      brandSub: "Restaurant password recovery",
      eyebrow: "Reset access",
      title: "Reset your restaurant dashboard password",
      text: "Enter the email connected to your AI Restaurant Call Assistant account. We will send a secure reset link to continue.",
      emptyError: "Enter your restaurant client email to receive a reset link.",
      success: "Password reset email sent. Check your inbox and open the secure reset link.",
      failed: "Could not send the password reset email.",
      loading: "Sending reset email...",
      submit: "Send reset email",
      helper: "The reset link will open the secure password page.",
    },
    reset: {
      brandSub: "Restaurant password reset",
      eyebrow: "Secure recovery",
      title: "Set a new restaurant dashboard password",
      text: "Use the secure recovery link from your email to create a new password for AI Restaurant Call Assistant analytics.",
      checking: "Validating your reset link...",
      invalid: "This reset link is invalid or expired.",
      success: "Your password has been updated. You can now sign in with your new password.",
      passwordPlaceholder: "Enter a new password",
      confirmPlaceholder: "Confirm your new password",
      shortPassword: "Password must be at least 8 characters.",
      mismatch: "Passwords do not match.",
      failed: "Could not update your password.",
      loading: "Updating password...",
      submit: "Update password",
    },
    dashboard: {
      nav: {
        overview: "Overview",
        locations: "Locations",
        handoffs: "Handoffs",
        quality: "Quality",
      },
      activeProduct: "Active product",
      mode: "Restaurant Mode",
      servicePage: "Service page",
      clientLogin: "Client login",
      logout: "Logout",
      signingOut: "Signing out...",
      home: "Home",
      restaurantAnalytics: "Restaurant analytics",
      last30Days: "Last 30 days",
      liveData: "Live data",
      error: "Error",
      supabaseError: "Data unavailable",
      overview: {
        eyebrow: "Restaurant analytics",
        title: "Your restaurant performance",
        text: "Live performance for your restaurant, including call volume, completed calls, escalations, unresolved requests, and site-level demand.",
        totalCalls: "Total Calls",
        totalCallsDetail: "Inbound calls received across your restaurant locations.",
        completedCalls: "Completed Calls",
        completedCallsDetail: "Calls resolved without needing manual staff intervention.",
        escalations: "Escalations",
        escalationsDetail: "Human handoffs created with routing context and priority.",
        fallbacks: "Needs review",
        fallbacksDetail: "Calls that needed backup handling or manual review.",
        businessInsights: "Business Insights",
        revenueProtection: "Revenue protection",
        businessDescription: "Signals that help operators understand where calls turn into risk, missed bookings, frustration, or staff follow-up.",
        topEscalationReasons: "Top escalation reasons",
        fallbackMissed: "Missed opportunities",
        frustrated: "Frustrated customers detected",
        followUp: "Calls needing follow-up",
        noEscalations: "No escalations",
        needsReview: "Needs review",
        locationsTitle: "Your Locations",
        bookingsHeader: "Bookings",
        reviewHeader: "Needs review",
        locationEyebrow: "Location analytics",
        locationDescription: "Site-level performance for your restaurant.",
        unavailable: "Analytics unavailable",
        loadErrorTitle: "Could not load the overview data.",
      },
      locations: {
        eyebrow: "Location analytics",
        title: "Locations",
        description: "Open a restaurant site to inspect calls, bookings, escalations, unresolved requests, and local service quality.",
        listTitle: "Location list",
        listEyebrow: "Restaurant sites",
        listDescription: "Choose a site to view its calls, bookings, and escalations.",
        noLocationsTitle: "No locations found",
        noLocationsText: "No sites are available for your current access.",
        loadErrorTitle: "Could not load locations.",
      },
      locationDetail: {
        eyebrow: "Location detail",
        description: "A site-level operating view for call demand, bookings, escalations, unresolved requests, and local service quality.",
        locationScope: "Location scope",
        calls: "Location Calls",
        callsDetail: "Inbound calls for this restaurant location.",
        bookings: "Bookings",
        bookingsDetail: "Bookings captured or qualified by AI.",
        handoffs: "Handoffs",
        handoffsDetail: "Calls escalated to staff with context.",
        fallbacks: "Needs review",
        fallbacksDetail: "Calls that needed backup handling or manual review.",
        recentCalls: "Recent calls",
        callActivity: "Call activity",
        recentDescription: "Recent calls or escalations for this site.",
        localTuning: "Local tuning",
        recommendations: "Recommendations",
        tuningDescription: "Site-specific signals to improve answers, FAQ coverage, staffing, and request handling.",
        recommendationHandoff: "of this site's calls required staff escalation. Review the top reasons and make sure the team receives complete context before peak service windows.",
        recommendationFallback: "of this site's calls needed backup handling. Check local menu details, opening hours, and booking availability coverage.",
        recommendationClear: "No urgent local tuning signals are visible for this site right now.",
        noAnalyticsTitle: "No location analytics found",
        noAnalyticsText: "No performance summary is available for this site in your current access.",
        noRecentTitle: "No recent call records",
        noRecentText: "There are no recent calls or escalations for this site.",
        noSignalTitle: "No tuning signal",
        noSignalText: "No quality signal is available for this site yet.",
        loadErrorTitle: "Could not load this location.",
      },
      handoffs: {
        eyebrow: "Human escalation",
        title: "Handoffs",
        description: "Track calls that required a human, including priority, reason, site, context quality, and resolution state.",
        operationsQueue: "Operations queue",
        open: "Open Handoffs",
        openDetail: "Escalations waiting for team action.",
        resolvedToday: "Resolved Today",
        resolvedDetail: "Handoffs closed by staff today.",
        avgAssignment: "Avg Assignment",
        avgDetail: "Average time before staff assignment.",
        highPriority: "High Priority",
        highDetail: "Sensitive requests needing faster attention.",
        queueTitle: "Handoff queue",
        queueEyebrow: "Escalation list",
        queueDescription: "Current requests filtered to your operating scope.",
        noHandoffsTitle: "No handoffs found",
        noHandoffsText: "There are no human escalation requests for your current access.",
        loadErrorTitle: "Could not load handoffs.",
      },
      quality: {
        eyebrow: "Quality assurance",
        title: "Quality",
        description: "Review assistant accuracy, memory usage, handoff completeness, fallback quality, and operational readiness.",
        qaQueue: "QA queue",
        noDataTitle: "No quality data found",
        noDataText: "No quality or escalation data is available for your current access.",
        summaryTitle: "Quality Summary",
        summaryEyebrow: "QA review",
        summaryDescription: "Operational quality checks from call understanding, conversation review, escalation quality, and memory usage.",
        metrics: {
          intentAccuracy: "Intent accuracy",
          memoryMatch: "Memory match rate",
          handoffCompleteness: "Escalation quality",
          reminderCoverage: "Reminder coverage",
        },
        reviewedCalls: "Reviewed Calls",
        reviewedDetail: "Calls sampled for QA in the current period.",
        passRate: "Pass Rate",
        passDetail: "Calls that met quality standards.",
        needsTuning: "Needs Tuning",
        needsTuningDetail: "Calls marked for prompt or routing improvement.",
        criticalQa: "Critical QA",
        criticalDetail: "Quality issues that need immediate review.",
        reviewQueue: "Review queue",
        nextActions: "Next actions",
        reviewDescription: "Quality notes, conversation reviews, and improvement actions.",
        noReviewTitle: "No review actions",
        noReviewText: "No quality review actions are available for your current access.",
        topEscalation: "Top Escalation Reasons",
        handoffDrivers: "Human handoff drivers",
        escalationDescription: "Reasons calls leave automation and require restaurant staff or manager review.",
        noEscalationTitle: "No escalation reasons",
        noEscalationText: "No escalation reason data is available for your current access.",
        missedTitle: "Missed Opportunities",
        leakage: "Revenue leakage",
        missedDescription: "Conversion risks caused by missing information, incomplete bookings, or unresolved requests.",
        noFallbackTitle: "No missed opportunities",
        noFallbackText: "No missed opportunities are detected for your current access.",
        frustratedTitle: "Frustrated Customers Detected",
        sentiment: "Sentiment monitoring",
        frustratedDescription: "Signals that should be reviewed before they become public feedback or lost repeat visits.",
        noFrustrationTitle: "No frustration signals",
        noFrustrationText: "No negative sentiment or urgent-language signals are available for your current access.",
        followUpTitle: "Calls Needing Follow-up",
        openLoop: "Open operational loop",
        followUpDescription: "Calls that should move into staff workflow, CRM notes, manager review, or guest callback.",
        noFollowUpTitle: "No follow-up calls",
        noFollowUpText: "No follow-up actions are currently attached to calls in your current access.",
        loadErrorTitle: "Could not load quality data.",
      },
    },
  },
} as const;
