import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { businessAliases, targetedAliasQuery, classifyWebsiteUrl, CommercialOfficialWebsiteResolver, evaluateBusinessResolution, resolveBusinessPresence } from "./business-resolution-v2";
import { robotsAllows } from "./robots-policy";
import { targetedSearch } from "./resolver-search";
import { commercialBusinessView, filterBusinessViews } from "./business-review-model";
import { rootInstagramHandle } from "./structured-instagram-resolver";
import type { StructuredCandidate } from "./structured-discovery-contract";
const at="2026-09-27T00:00:00Z";
const c:StructuredCandidate={provider:"future_registry",externalId:"AbC-1",country:"GB",businessName:"Legal Company Ltd",city:"London",postalCode:"W1A 1AA",address:"12 Market Street",department:"London",activity:{code:"x",label:"Beauty",nomenclature:"fixture"},eligibility:{prospectingEligible:true,reason:"fixture",checkedAt:at,policyVersion:"fixture",establishmentDiffusion:"O",legalUnitDiffusion:"O"},source:{url:"https://registry.example/business/AbC-1",license:"fixture",attribution:"fixture",observedAt:at},business_aliases:[{value:"The Beauty Studio",alias_type:"trade_name",provider:"future_registry",evidence:"registered trading name",observed_at:at}],verifiedPhone:"02079460000"};
const site={url:"https://beauty.example/",text:"The Beauty Studio 12 Market Street London W1A 1AA",links:["https://instagram.com/beauty_studio/"]};
const hit={url:site.links[0],title:"The Beauty Studio",snippet:"London"};
test("future provider trade alias takes priority without invented alias",()=>{assert.equal(targetedAliasQuery(c),'"The Beauty Studio" "London" Instagram');assert.equal(businessAliases(c)[0].alias_type,"trade_name");assert.equal(businessAliases({...c,business_aliases:[]})[0].alias_type,"provider_selected_name");});
for(const domain of ["infobel.com","unboncoiffeur.fr","alentoor.fr","pagesjaunes.fr"])test(`directory ${domain} never official`,()=>{assert.equal(classifyWebsiteUrl(`https://${domain}/`),"DIRECTORY");assert.equal(new CommercialOfficialWebsiteResolver().evaluate(c,{...site,url:`https://${domain}/`},at).classification,"DIRECTORY");});
for(const domain of ["planity.com","treatwell.fr","fresha.com"])test(`shared platform ${domain} never official`,()=>assert.equal(classifyWebsiteUrl(`https://${domain}/`),"SHARED_PLATFORM"));
test("official website needs establishment identity not name or city alone",()=>{const r=new CommercialOfficialWebsiteResolver();assert.equal(r.evaluate(c,site,at).classification,"OFFICIAL_SITE");assert.equal(r.evaluate(c,{...site,text:"The Beauty Studio London"},at).classification,"UNKNOWN");assert.equal(classifyWebsiteUrl(hit.url),"SOCIAL_NETWORK");});
for(const [body,path,expected] of [
 ["User-agent: *\nDisallow: /private/","/",true],
 ["User-agent: *\nDisallow: /private/","/private/data",false],
 ["User-agent: *\nDisallow: /","/",false],
 ["User-agent: *\nDisallow: /\nAllow: /public/","/public/a",true],
 ["User-agent: *\nDisallow: /a\nAllow: /a","/a",true],
 ["User-agent: *\nDisallow: /\nUser-agent: BMBDiscoveryBot\nAllow: /","/",true],
 ["User-agent: BMBDiscoveryBot\nDisallow: /x\nUser-agent: bmbdiscoverybot\nDisallow: /y","/y",false],
 ["User-agent: OtherBot\nDisallow: /","/",true],
 ["User-agent: *\nDisallow: /*.pdf$","/file.pdf",false],
 ["User-agent: *\nDisallow: /café","/caf%C3%A9",false],
 ["User-agent: *\nDisallow: /%70rivate","/private",false],
] as const)test(`robots ${path} ${expected}: ${body}`,()=>assert.equal(robotsAllows(body,path),expected));
test("official establishment direct profile is HIGH with evidence",()=>{const r=evaluateBusinessResolution(c,[],[site],[],at);assert.equal(r.match.confidence,"HIGH");assert.equal(r.profileScope,"DEDICATED_ESTABLISHMENT_PROFILE");assert.ok(r.evidence.some(e=>e.type==="OFFICIAL_SITE_INSTAGRAM_LINK"&&e.observed_at===at));});
test("same-origin contact identity corroborates homepage link; other origins do not",()=>{const home={...site,text:"The Beauty Studio",links:site.links},contact={...site,url:site.url+"contact",links:[]};assert.equal(evaluateBusinessResolution(c,[],[home,contact]).match.confidence,"HIGH");assert.equal(evaluateBusinessResolution(c,[],[home,{...contact,url:"https://other.example/contact"}]).match.confidence,"LOW");assert.notEqual(evaluateBusinessResolution(c,[],[home,{...contact,text:contact.text+" Nos salons"}]).match.confidence,"HIGH");});
test("ineligible V2 candidate causes no external lookup",async()=>{await resolveBusinessPresence({...c,eligibility:{...c.eligibility,prospectingEligible:false}},{search:async()=>{throw Error("unexpected");},site:async()=>{throw Error("unexpected");}});});
test("alias city alone remains MEDIUM and missing identity LOW",()=>{assert.equal(evaluateBusinessResolution(c,[hit],[]).match.confidence,"MEDIUM");assert.equal(evaluateBusinessResolution(c,[],[]).match.confidence,"LOW");});
test("backlink and independent address corroborate, contradiction blocks",()=>{const p={url:hit.url,alias:"The Beauty Studio",city:c.city,address:c.address,phone:c.verifiedPhone,website:site.url,observed_at:at};const r=evaluateBusinessResolution(c,[],[{...site,links:[]}],[p],at);assert.equal(r.match.confidence,"HIGH");assert.ok(r.evidence.some(e=>e.type==="PHONE_MATCH"));assert.equal(evaluateBusinessResolution(c,[],[site],[{...p,city:"Manchester"}]).match.confidence,"LOW");});
test("brand-wide and multiple accounts never HIGH",()=>{assert.notEqual(evaluateBusinessResolution(c,[],[{...site,text:site.text+" Our locations"}]).match.confidence,"HIGH");assert.notEqual(evaluateBusinessResolution(c,[hit],[site],[{url:hit.url,sharedBrand:true,observed_at:at}]).match.confidence,"HIGH");assert.notEqual(evaluateBusinessResolution(c,[],[{...site,links:[...site.links,"https://instagram.com/another/"]}]).match.confidence,"HIGH");});
test("profile URLs reject content, shares, credentials and non-https",()=>{for(const u of ["https://instagram.com/p/a","https://instagram.com/reels/","https://instagram.com/stories/a/","https://instagram.com/share/","https://u:p@instagram.com/a","http://instagram.com/a"])assert.equal(rootInstagramHandle(u),null);});
test("one targeted lookup and max two same-origin pages",async()=>{let searches=0,pages=0;const r=await resolveBusinessPresence(c,{search:async()=>{searches++;return [{url:site.url,title:"The Beauty Studio",snippet:"London"}];},site:async url=>{pages++;return {...site,url,links:[...site.links,"https://beauty.example/contact","https://evil.example/contact"]};}});assert.equal(searches,1);assert.equal(pages,2);assert.equal(r.match.confidence,"HIGH");});
for(const [payload,status,outcome] of [[{organic_results:[{link:hit.url,title:hit.title,snippet:hit.snippet}]},200,"SUCCESS"],[{organic_results:[]},200,"EMPTY_RESULTS"],[{},200,"INVALID_PAYLOAD"],[{error:"provider refusal"},200,"PROVIDER_ERROR"],[{},429,"HTTP_ERROR"]] as const)test(`search ${outcome}`,async()=>assert.equal((await targetedSearch("fixture","secret",async()=>new Response(JSON.stringify(payload),{status}))).outcome,outcome));
test("parser and timeout errors retain safe causes",async()=>{assert.equal((await targetedSearch("fixture","secret",async()=>new Response("not json"))).outcome,"PARSER_ERROR");const r=await targetedSearch("fixture","secret",async()=>{throw new DOMException("secret","TimeoutError");});assert.equal(r.outcome,"TIMEOUT");assert.ok(!JSON.stringify(r).includes("secret"));});
for(const confidence of ["HIGH","MEDIUM","LOW"] as const)test(`UI ${confidence} unscored and provider secondary`,()=>{const resolution=evaluateBusinessResolution(c,[],[site]);resolution.match.confidence=confidence;const v=commercialBusinessView({id:"i",business_id:"b",source_snapshot_safe:c,enrichment_snapshot_safe:{resolver_v2:resolution}});assert.equal(v.score,null);assert.equal(v.recommendedAngle,null);assert.equal(v.country,"GB");assert.equal(v.qualificationStatus,confidence==="HIGH"?"Needs Review":confidence==="MEDIUM"?"Hold":"Unresolved");assert.equal(filterBusinessViews([v],"FR","").length,0);assert.equal(filterBusinessViews([v],"GB","legal").length,1);});
test("UI shares SA components and CSS",()=>{const read=(f:string)=>readFileSync(new URL(`../../app/instagram-dashboard/commercial/${f}`,import.meta.url),"utf8");for(const f of ["CommercialLeadReviewQueue.tsx","CommercialIdentityWorkspace.tsx"])assert.match(read(f),/CommercialQueueShell/);for(const f of ["CommercialLeadDetail.tsx","CommercialIdentityWorkspace.tsx"])assert.match(read(f),/CommercialContextSection/);assert.match(read("CommercialIdentityWorkspace.tsx"),/CommercialLeadReviewWorkspace.module.css/);assert.match(read("CommercialIdentityWorkspace.tsx"),/<details/);assert.doesNotMatch(read("CommercialIdentityWorkspace.tsx"),/approveCommercial|sendEmail|analyzeCommercial/);});
test("reprocess has no Sirene, AI, lead creation, enrichment dependency",()=>{const src=readFileSync(new URL("./resolver-reprocess-service.ts",import.meta.url),"utf8");assert.doesNotMatch(src,/SireneProvider|discovery-ai|discovery-scoring|lookupInstagramPublicProfile|persist_structured_scored|create_structured_commercial|sendEmail/);assert.match(src,/await reserve\("search",query\)/);});
