export type InstagramSettingsDefaults = Record<string, string | number | boolean>;
export type InstagramFiltersDefaults = Record<string, string | number | boolean>;

export const defaultInstagramSettings: InstagramSettingsDefaults = {
  username: "",
  display_name: "",
  device_name: "",
  device_udid: "",
  email: "",
  password: "",
  app_package: "com.instagram.android",
  account_status: "active",
  campaign_name: "Default campaign",
  timeslot_start: "09:00",
  timeslot_end: "18:00",
  pause_account_until: "",
  welcome_dm_message: "",
  cold_dm_message: "",
  sort_followers_mode: "recent",
  source_accounts: "",
  last_error: "",
  last_successful_action: "",
  current_run_status: "idle",
  two_fa_enabled: false,
  cloned_app_mode: false,
  randomize_start_enabled: true,
  follow_enabled: false,
  unfollow_enabled: false,
  like_enabled: false,
  story_watch_enabled: true,
  welcome_dm_enabled: true,
  cold_dm_enabled: false,
  check_chat_before_welcoming: true,
  send_enabled: false,
  safe_review_mode: true,
  followback_on_followers: false,
  unfollow_non_followers: false,
  unfollow_any: false,
  mute_posts_after_follow: false,
  mute_stories_after_follow: false,
  do_follows_first: true,
  delete_interacted_users: false,
  change_source_if_crash: true,
  fling_when_skipped: true,
  end_if_follow_limit_reached: true,
  end_if_dm_limit_reached: true,
  end_if_likes_limit_reached: true,
  warmup_mode: true,
  stop_on_suspicious_screen: true,
  stop_on_login_challenge: true,
  stop_on_checkpoint: true,
  stop_on_repeated_navigation_failure: true,
  disable_block_detection: false,
  relog_after_block: true,
  rotate_ip: false,
  restart_uiautomator2: true,
  close_apps: true,
  close_apps_device: false,
  log_out_all_before_session: false,
  screen_sleep: false,
  screen_record: false,
  debug_mode: false,
  dry_run_enabled: true,
  manual_stop_requested: false,
  total_sessions: 1,
  stop_interactions_after_minutes: 45,
  timeout_startup_seconds: 120,
  pause_account_days: 0,
  speed_multiplier: 1,
  follow_limit: 20,
  total_follows_limit: 100,
  follow_percentage: 100,
  total_unfollows_limit: 0,
  unfollow_delay_days: 7,
  total_likes_limit: 100,
  likes_per_follow_min: 0,
  likes_per_follow_max: 2,
  likes_percentage: 100,
  watch_photo_time_min: 3,
  watch_photo_time_max: 8,
  watch_video_time_min: 5,
  watch_video_time_max: 18,
  max_dm_per_run: 2,
  max_consecutive_dms: 3,
  max_followback_skips: 50,
  max_followback_ignore: 200,
  unfollow_skip_limit: 50,
  truncate_sources_min: 20,
  truncate_sources_max: 80,
  skipped_posts_limit: 20,
  total_interactions_limit: 120,
  total_successful_interactions_limit: 80,
  interactions_count: 0,
  interact_percentage: 100,
  max_actions_per_hour: 30,
  max_actions_per_day: 120,
  random_delay_min_seconds: 8,
  random_delay_max_seconds: 20,
  random_pause_every_actions: 15,
  long_break_after_interactions: 45,
  long_break_min_minutes: 8,
  long_break_max_minutes: 18,
  max_repeated_errors: 5,
  relog_delay_seconds: 120,
  total_crashes_limit: 3,
};

export const safeSetupSettings: InstagramSettingsDefaults = {
  dry_run_enabled: true,
  send_enabled: false,
  safe_review_mode: true,
  follow_enabled: false,
  like_enabled: false,
  story_watch_enabled: false,
  max_dm_per_run: 1,
  random_delay_min_seconds: 8,
  random_delay_max_seconds: 20,
};

export const defaultInstagramFilters: InstagramFiltersDefaults = {
  disable_filters: false,
  skip_followers: true,
  skip_following: true,
  skip_non_business_profiles: false,
  skip_business_profiles: false,
  follow_private_profiles: false,
  follow_only_private_profiles: false,
  dm_private_profiles: false,
  min_followers: 1,
  max_followers: 1000000000000,
  min_following: 1,
  max_following: 1000000000000,
  min_posts: 1,
  blacklisted_words: "",
  mandatory_words: "",
  whitelist_words: "",
  blacklist_accounts: "",
};

export const safeSetupFilters: InstagramFiltersDefaults = {
  skip_followers: true,
  skip_following: true,
  skip_business_profiles: false,
  skip_non_business_profiles: false,
  min_followers: 1,
  min_following: 1,
  min_posts: 1,
};

export const defaultSafeSetupTemplate = {
  name: "Default Safe Setup",
  description: "Safe baseline for new Instagram Account setup.",
  template_type: "full",
  settings_payload: safeSetupSettings,
  filters_payload: safeSetupFilters,
  is_default: true,
};
